workspace = { members = ["mig_egg"] }
[package]
name = "MIGBalance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mignite = { path = "mignite" }
egg = { version = "0.9.5", features = ["lp"] }
