[package]
name = "mig_egg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = { version = "0.9.5", features = ["lp"] }
pyo3 = { version = "0.20", features = ["extension-module"] }
